In [14]:
import numpy as np

print("Question 1 - Basic Array Operations")
arr = np.array([1, 2, 3, 4, 5])
print("Original array:", arr)

Question 1 - Basic Array Operations
Original array: [1 2 3 4 5]


In [15]:
print("Q1(a) - After adding 2:", arr + 2)

Q1(a) - After adding 2: [3 4 5 6 7]


In [16]:
print("Q1(b) - After multiplying by 3:", arr * 3)

Q1(b) - After multiplying by 3: [ 3  6  9 12 15]


In [17]:
print("Q1(c) - After dividing by 2:", arr / 2)

Q1(c) - After dividing by 2: [0.5 1.  1.5 2.  2.5]


In [18]:
print("\nQuestion 2 - Array Manipulations")
print("Q2(a) - Reverse array")
arr = np.array([1, 2, 3, 6, 4, 5])
print("Original array:", arr)
print("Reversed array:", arr[::-1])

print("\nQ2(b-i) - Most frequent values in array x")
x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1])
print("Array x:", x)
values, counts = np.unique(x, return_counts=True)
most_frequent = values[counts == counts.max()]
indices = np.where(np.isin(x, most_frequent))[0]
print("Most frequent value in x:", most_frequent)
print("Indices:", indices)



Question 2 - Array Manipulations
Q2(a) - Reverse array
Original array: [1 2 3 6 4 5]
Reversed array: [5 4 6 3 2 1]

Q2(b-i) - Most frequent values in array x
Array x: [1 2 3 4 5 1 2 1 1 1]
Most frequent value in x: [1]
Indices: [0 5 7 8 9]


In [19]:
print("\nQ2(b-ii) - Most frequent values in array y")
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])
values, counts = np.unique(y, return_counts=True)
most_frequent = values[counts == counts.max()]
indices = np.where(np.isin(y, most_frequent))[0]
print("Most frequent value in y:", most_frequent)
print("Indices:", indices)



Q2(b-ii) - Most frequent values in array y
Most frequent value in y: [1 3]
Indices: [0 1 2 4 8 9]


In [20]:
print("\nQuestion 3 - 2D Array Indexing")
arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
print("Original 2D array:")
print(arr)





Question 3 - 2D Array Indexing
Original 2D array:
[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [21]:
print("Q3(a) - 1st row, 2nd column:", arr[0, 1])

Q3(a) - 1st row, 2nd column: 20


In [22]:
print("Q3(b) - 3rd row, 1st column:", arr[2, 0])

Q3(b) - 3rd row, 1st column: 70


In [23]:
print("\nQuestion 4 - Array Creation and Properties")
naman_singh = np.linspace(10, 100, 25)
print("Array:", naman_singh)
print("Q4(a) - Dimensions:", naman_singh.ndim)
print("Q4(b) - Shape:", naman_singh.shape)
print("Q4(c) - Total elements:", naman_singh.size)
print("Q4(d) - Data type:", naman_singh.dtype)
print("Q4(e) - Total bytes:", naman_singh.nbytes)
reshaped = naman_singh.reshape(-1, 1)
print("Q4(f) - Reshaped array:")
print(reshaped)
print("Q4(g) - Using T attribute:")
print(naman_singh.reshape(-1, 1).T)


Question 4 - Array Creation and Properties
Array: [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
Q4(a) - Dimensions: 1
Q4(b) - Shape: (25,)
Q4(c) - Total elements: 25
Q4(d) - Data type: float64
Q4(e) - Total bytes: 200
Q4(f) - Reshaped array:
[[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]
Q4(g) - Using T attribute:
[[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
   47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
   85.    88.75  92.5   96.25 100.  ]]


In [24]:
print("\nQuestion 5 - 2D Array Operations")
ucs420_naman_singh = np.array([[10, 20, 30, 40],
                              [50, 60, 70, 80],
                              [90, 15, 20, 35]])
print("Q5 - Creating 2D Array with three rows and four columns:")
print(ucs420_naman_singh)
print("Q5(a) - Mean:", np.mean(ucs420_naman_singh))
print("Q5(b) - Median:", np.median(ucs420_naman_singh))
print("Q5(c) - Max:", np.max(ucs420_naman_singh))
print("Q5(d) - Min:", np.min(ucs420_naman_singh))
print("Q5(e) - Unique elements:", np.unique(ucs420_naman_singh))

print("\nQ5(f) - Reshaped to 4x3 (reshaped_ucs420_naman_singh):")
reshaped_ucs420_naman_singh = ucs420_naman_singh.reshape(4, 3)
print(reshaped_ucs420_naman_singh)

print("\nQ5(g) - Resized to 2x3 (resized_ucs420_naman_singh):")
resized_ucs420_naman_singh = np.resize(ucs420_naman_singh, (2, 3))
print(resized_ucs420_naman_singh)


Question 5 - 2D Array Operations
Q5 - Creating 2D Array with three rows and four columns:
[[10 20 30 40]
 [50 60 70 80]
 [90 15 20 35]]
Q5(a) - Mean: 43.333333333333336
Q5(b) - Median: 37.5
Q5(c) - Max: 90
Q5(d) - Min: 10
Q5(e) - Unique elements: [10 15 20 30 35 40 50 60 70 80 90]

Q5(f) - Reshaped to 4x3 (reshaped_ucs420_naman_singh):
[[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]

Q5(g) - Resized to 2x3 (resized_ucs420_naman_singh):
[[10 20 30]
 [40 50 60]]
